version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-whatsapp-bot
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=whatsapp-bot
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 